#pragma once
#define WINDOW_CLASS_NAME L"Aladdin"
#define MAIN_WINDOW_TITLE L"Aladdin"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(255, 255, 200)
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define MAX_FRAME_RATE 120

#define ID_TEX_ALADDIN 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20

#define ID_TEX_ALADDIN 0

#define ALADDIN_WALKING_SPEED		0.1f 
//0.1f
#define ALADDIN_JUMP_SPEED_Y		0.5f
#define ALADDIN_JUMP_DEFLECT_SPEED 0.2f
#define ALADDIN_GRAVITY			0.002f
#define ALADDIN_DIE_DEFLECT_SPEED	 0.5f

#define ALADDIN_STATE_IDLE			0
#define ALADDIN_STATE_WALKING_RIGHT	100
#define ALADDIN_STATE_WALKING_LEFT	200
#define ALADDIN_STATE_JUMP			300
#define ALADDIN_STATE_DIE				400

#define ALADDIN_ANI_IDLE		0

#define ALADDIN_ANI_WALKING		1

#define ALADDIN_ANI_DIE				8

#define ALADDIN_BBOX_WIDTH  54
#define ALADDIN_BBOX_HEIGHT 46

#define ALADDIN_UNTOUCHABLE_TIME 5000