#pragma once
#define WINDOW_CLASS_NAME L"Aladdin"
#define MAIN_WINDOW_TITLE L"Aladdin"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(255, 255, 200)
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 384

#define MAX_FRAME_RATE 120

//ID TEXTURES
#define ID_TEX_ALADDIN 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20

#define ID_TEX_MAP_ONE -10

//ID SPRITES
#define ID_SPRITE_MAP_ONE -10

//ID ANIMATIONS

//ID OBJECTS
#define	OBJECT_GROUND -100
#define OBJECT_PILLAR_1 -90
#define OBJECT_PILLAR_2 -80
#define OBJECT_PILLAR_3 -70
#define OBJECT_PILLAR_4 -60
#define OBJECT_ROCK -60

//ALADDIN
#define ALADDIN_WALKING_SPEED		0.1f 
//0.1f
#define ALADDIN_JUMP_SPEED_Y		0.5f
#define ALADDIN_JUMP_DEFLECT_SPEED 0.2f
#define ALADDIN_GRAVITY			0.002f
#define ALADDIN_DIE_DEFLECT_SPEED	 0.5f

#define ALADDIN_STATE_IDLE			0
#define ALADDIN_STATE_WALKING_RIGHT	100
#define ALADDIN_STATE_WALKING_LEFT	200
#define ALADDIN_STATE_JUMP			300
#define ALADDIN_STATE_DIE				400

#define ALADDIN_ANI_IDLE		0

#define ALADDIN_ANI_WALKING		1

#define ALADDIN_ANI_DIE			8

#define ALADDIN_BBOX_WIDTH  54
#define ALADDIN_BBOX_HEIGHT 46

#define ALADDIN_UNTOUCHABLE_TIME 5000

//Ground
#define GROUND_BBOX_WIDTH				32
#define GROUND_BBOX_HEIGHT				5