#pragma once
#define WINDOW_CLASS_NAME L"Simon"
#define MAIN_WINDOW_TITLE L"Simon"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)
#define SCREEN_WIDTH  514
#define SCREEN_HEIGHT 470

#define MAX_FRAME_RATE 120

//ID TEXTURES
#define ID_TEX_SIMON              0
#define ID_TEX_BRICK_OUT_CASTLE   1
#define ID_TEX_TORCH              2 
#define ID_TEX_WHIP				  3
#define ID_TEX_BRICK_SCENE_ONE	  4
#define ID_TEX_CANDLE	          5
#define ID_TEX_ITEM_WHIP		  200
#define ID_TEX_ITEM_HEART		  201
#define ID_TEX_COLLISION_EFFECT	  800
#define ID_TEX_DEAD_EFFECT		  801
#define ID_TEX_HP				  900
#define ID_TEX_ITEM_BOARD_HEART	  901
#define ID_TEX_MAP_OUT_CASTLE     1000

//ID SPRITES
#define ID_SPRITE_MAP_OUT_CASTLE  1000


// config game
#define DEVIATION_X						32


//ID OBJECTS
#define	OBJECT_BRICK_OUT_CASTLE			1
#define	OBJECT_TORCH					2
#define OBJECT_BRICK_SENCE_ONE			3
#define OBJECT_CANDLE					4

//====
//SIMON
//====
#define SIMON_WALKING_SPEED		0.1f 
#define SIMON_JUMP_SPEED_Y		0.5f
#define SIMON_JUMP_DEFLECT_SPEED	0.2f
#define SIMON_GRAVITY				0.002f
#define SIMON_DIE_DEFLECT_SPEED		0.5f
#define SIMON_HP					16

#define SIMON_ATTACK_TIME			150*3-10


//simon state
#define SIMON_STATE_IDLE			100

#define SIMON_STATE_WALKING_RIGHT	200
#define SIMON_STATE_WALKING_LEFT	300
#define SIMON_STATE_JUMP			400
#define SIMON_STATE_SIT_DOWN		500
#define SIMON_STATE_FIGHTING		600

#define SIMON_STATE_DIE				10000

//simon ani
#define SIMON_ANI_IDLE_LEFT						0
#define SIMON_ANI_IDLE_RIGHT					1
#define SIMON_ANI_WALKING_LEFT					2
#define SIMON_ANI_WALKING_RIGHT					3
#define SIMON_ANI_SIT_DOWN_LEFT					4
#define SIMON_ANI_SIT_DOWN_RIGHT				5
#define SIMON_ANI_FIGHTING_LEFT					6
#define SIMON_ANI_FIGHTING_RIGHT				7
#define SIMON_ANI_SIT_DOWN_FIGHTING_LEFT		8
#define SIMON_ANI_SIT_DOWN_FIGHTING_RIGHT		9
#define SIMON_ANI_JUMP_FIGHTING_LEFT			10
#define SIMON_ANI_JUMP_FIGHTING_RIGHT			11

#define SIMON_ANI_DIE							46

// size bbox simon
#define SIMON_BBOX_WIDTH  32
#define SIMON_BBOX_HEIGHT 62

#define SIMON_SIT_BBOX_WIDTH  32
#define SIMON_SIT_BBOX_HEIGHT 46


#define SIMON_UNTOUCHABLE_TIME					2000
#define SIMON_HURTABLE_TIME						600

#define SIMON_MAX_HP 8

//whip
#define WHIP_LEVEL_1	1
#define WHIP_LEVEL_2	2
#define WHIP_LEVEL_3	3

#define WHIP_LEVEL_1_ANI_PREPARE_LEFT		0
#define WHIP_LEVEL_1_ANI_LEFT				1
#define WHIP_LEVEL_1_ANI_PREPARE_RIGHT		2
#define WHIP_LEVEL_1_ANI_RIGHT				3
#define WHIP_LEVEL_2_ANI_PREPARE_LEFT		4
#define WHIP_LEVEL_2_ANI_LEFT				5
#define WHIP_LEVEL_2_ANI_PREPARE_RIGHT		6
#define WHIP_LEVEL_2_ANI_RIGHT				7
#define WHIP_LEVEL_3_ANI_PREPARE_LEFT		8
#define WHIP_LEVEL_3_ANI_LEFT				9
#define WHIP_LEVEL_3_ANI_PREPARE_RIGHT		10
#define WHIP_LEVEL_3_ANI_RIGHT				11

#define WHIP_STATE_PREPARE 0
#define WHIP_STATE_HIT 1

#define WHIP_DELTA_POSITION_Y		16

#define WHIP_DELTA_POSITION_BOX_HEIGHT		18

#define WHIP_LEVEL_1_BBOX_WIDTH		44
#define WHIP_LEVEL_1_BBOX_HEIGHT	14
#define WHIP_LEVEL_2_BBOX_WIDTH		44
#define WHIP_LEVEL_2_BBOX_HEIGHT	14
#define WHIP_LEVEL_3_BBOX_WIDTH		74
#define WHIP_LEVEL_3_BBOX_HEIGHT	14

//item
#define ITEM_WHIP			9006
#define ITEM_BALL			9001
#define ITEM_MONEY			9002
#define ITEM_SMALL_HEART	9003
#define ITEM_BIG_HEART		9004
#define ITEM_ROAST			9005
#define ITEM_AXE			9007
#define ITEM_BOOMERANG		9008
#define ITEM_HOLY_WATER		9009
#define ITEM_DAGGER			9010
#define ITEM_STOP_WATCH		9011
#define ITEM_INVISIBLE		9012
#define ITEM_UPGRADE_1		9013
#define ITEM_UPGRADE_2		9014
#define ITEM_CROSS			9015
#define ITEM_MONEY_WHITE	9016
#define ITEM_MONEY_RED		9017
#define ITEM_MONEY_PURPLE	9018


#define ITEM_STATE_UP				9000
#define ITEM_STATE_IDLE				9001


//item board
#define ITEM_BOARD_HEART			50010

