#pragma once
#define WINDOW_CLASS_NAME L"Simon"
#define MAIN_WINDOW_TITLE L"Simon"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)
#define SCREEN_WIDTH 272
#define SCREEN_HEIGHT 240

#define MAX_FRAME_RATE 120

#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_SETTINGS 0
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6

#define MAX_SCENE_LINE 1024

//ID TEXTURES
#define ID_TEX_SIMON              0
#define ID_TEX_BRICK_OUT_CASTLE   1
#define ID_TEX_TORCH              2 
#define ID_TEX_WHIP				  3
#define ID_TEX_BRICK_SCENE_ONE	  4
#define ID_TEX_CANDLE	          5
#define ID_TEX_ITEM_WHIP		  200
#define ID_TEX_ITEM_HEART		  201
#define ID_TEX_COLLISION_EFFECT	  800
#define ID_TEX_DEAD_EFFECT		  801
#define ID_TEX_HP				  900
#define ID_TEX_ITEM_BOARD_HEART	  901
#define ID_TEX_MAP_OUT_CASTLE     1000

//ID SPRITES
#define ID_SPRITE_MAP_OUT_CASTLE  1000


// config game
#define DEVIATION_X						0
#define DEVIATION_Y						20

//ID OBJECTS
#define	OBJECT_TYPE_SIMON				1

#define	OBJECT_TYPE_TORCH				10
#define OBJECT_TYPE_CANDLE				11
#define OBJECT_TYPE_GATE				12
#define	OBJECT_TYPE_BOUNGDING_MAP		13
#define OBJECT_TYPE_PORTAL				14
#define	OBJECT_TYPE_BOTTOM_STAIR		15
#define OBJECT_TYPE_TOP_STAIR			16
#define OBJECT_TYPE_GROUND				17
#define OBJECT_TYPE_MOVING_FLATFORM     18

#define OBJECT_TYPE_ITEM_WHIP			100
#define	OBJECT_TYPE_ITEM_SMALL_HEART	101
#define	OBJECT_TYPE_ITEM_HEART			102
#define	OBJECT_TYPE_ITEM_KNIFE			103
#define OBJECT_TYPE_ITEM_AXE			104
#define	OBJECT_TYPE_ITEM_BOOMERANG		105
#define OBJECT_TYPE_VAMPIRE_BAT         202
#define OBJECT_TYPE_BLACK_KNGHT         204

//====
//SIMON
//====
#define SIMON_WALKING_SPEED		0.05f 
#define SIMON_JUMP_SPEED_Y		0.204f
#define SIMON_JUMP_DEFLECT_SPEED	0.2f
#define SIMON_GRAVITY				0.0007f
#define SIMON_DIE_DEFLECT_SPEED		0.5f
#define SIMON_HP					16

#define SIMON_ATTACK_TIME			340
#define TIME_FREEZE_MAX 500


//simon state
#define SIMON_STATE_IDLE					100

#define SIMON_STATE_WALK_RIGHT				200
#define SIMON_STATE_WALK_LEFT				300
#define SIMON_STATE_JUMP					400
#define SIMON_STATE_SIT_DOWN				500
#define SIMON_STATE_CLIMB_STAIR_ASCEND		600
#define SIMON_STATE_CLIMB_STAIR_DESCEND		700
#define SIMON_STATE_FIGHTING				800
#define SIMON_STATE_INTRO					900
#define SIMON_STATE_HURT					900

#define SIMON_STATE_DIE				10000

//simon ani
#define SIMON_ANI_IDLE_LEFT						0
#define SIMON_ANI_IDLE_RIGHT					1
#define SIMON_ANI_WALKING_LEFT					2
#define SIMON_ANI_WALKING_RIGHT					3
#define SIMON_ANI_SIT_DOWN_LEFT					4
#define SIMON_ANI_SIT_DOWN_RIGHT				5
#define SIMON_ANI_CIMB_STAIR_ASCEND_LEFT		6
#define SIMON_ANI_CIMB_STAIR_ASCEND_RIGHT		7
#define SIMON_ANI_CIMB_STAIR_DESCEND_LEFT		8
#define SIMON_ANI_CIMB_STAIR_DESCEND_RIGHT		9
#define SIMON_ANI_HURT_LEFT						10
#define SIMON_ANI_HURT_RIGHT					11
#define SIMON_ANI_DEATH_LEFT					12
#define SIMON_ANI_DEATH_RIGHT					13
#define SIMON_ANI_FIGHTING_LEFT					14
#define SIMON_ANI_FIGHTING_RIGHT				15
#define SIMON_ANI_FIGHTING_SIT_LEFT				16
#define SIMON_ANI_FIGHTING_SIT_RIGHT			17
#define SIMON_ANI_FIGHTING_ASCEND_STAIR_LEFT	18
#define SIMON_ANI_FIGHTING_ASCEND_STAIR_RIGHT	19
#define SIMON_ANI_FIGHTING_DESCEND_STAIR_LEFT	20
#define SIMON_ANI_FIGHTING_DESCEND_STAIR_RIGHT	21
#define SIMON_ANI_INTRO							22
#define SIMON_ANI_IDLE_STAIR_ASCEND_LEFT		23
#define SIMON_ANI_IDLE_STAIR_ASCEND_RIGHT		24
#define SIMON_ANI_IDLE_STAIR_DESCEND_LEFT		25
#define SIMON_ANI_IDLE_STAIR_DESCEND_RIGHT		26


// size bbox simon
#define SIMON_BBOX_WIDTH  16
#define SIMON_BBOX_HEIGHT 31

#define SIMON_SIT_BBOX_WIDTH  32
#define SIMON_SIT_BBOX_HEIGHT 46


#define SIMON_UNTOUCHABLE_TIME					2000
#define SIMON_HURTABLE_TIME						600

#define SIMON_MAX_HP 8

//whip
#define WHIP_DAMAGE		2

#define WHIP_LEVEL_1	1
#define WHIP_LEVEL_2	2
#define WHIP_LEVEL_3	3

#define WHIP_LEVEL_1_ANI_PREPARE_LEFT		0
#define WHIP_LEVEL_1_ANI_LEFT				1
#define WHIP_LEVEL_1_ANI_PREPARE_RIGHT		2
#define WHIP_LEVEL_1_ANI_RIGHT				3
#define WHIP_LEVEL_2_ANI_PREPARE_LEFT		4
#define WHIP_LEVEL_2_ANI_LEFT				5
#define WHIP_LEVEL_2_ANI_PREPARE_RIGHT		6
#define WHIP_LEVEL_2_ANI_RIGHT				7
#define WHIP_LEVEL_3_ANI_PREPARE_LEFT		8
#define WHIP_LEVEL_3_ANI_LEFT				9
#define WHIP_LEVEL_3_ANI_PREPARE_RIGHT		10
#define WHIP_LEVEL_3_ANI_RIGHT				11

#define WHIP_STATE_PREPARE 0
#define WHIP_STATE_HIT 1

#define WHIP_DELTA_POSITION_Y		8

#define WHIP_DELTA_POSITION_BOX_HEIGHT		9
#define WHIP_DELTA_X_LEFT 6
#define WHIP_DELTA_X_RIGHT 5

#define WHIP_LEVEL_1_BBOX_WIDTH		24
#define WHIP_LEVEL_1_BBOX_HEIGHT	8
#define WHIP_LEVEL_2_BBOX_WIDTH		26
#define WHIP_LEVEL_2_BBOX_HEIGHT	6
#define WHIP_LEVEL_3_BBOX_WIDTH		40
#define WHIP_LEVEL_3_BBOX_HEIGHT	6

//Standard Items
#define ITEM_MORNING_STAIR					0
#define ITEM_SMALL_HEART					1
#define ITEM_LARGE_HEART					2
#define ITEM_MONEY_BAG_RED					3
#define ITEM_MONEY_BAG_PURPLE				4
#define ITEM_MONEY_BAG_WHITE				5

//Weapons
#define ITEM_DAGGER							6
#define ITEM_AXE							7
#define ITEM_HOLY_WATER						8
#define ITEM_BOOMERANG						9
#define ITEM_STOP_WATCH						10

//Special Items
#define ITEM_CROSS							11
#define ITEM_INVISIBILITY_POTION			12
#define ITEM_PORK_CHOP						13
#define ITEM_DOUBLE_SHOT					14
#define ITEM_TRIPLE_SHOT					15
#define ITEM_BONUSES						16
#define ITEM_MAGIC_CRYSTAL					17
#define ITEM_CROWN							18
#define ITEM_CHEST							19


//item board
#define ITEM_BOARD_DAGGER					40008
#define ITEM_BOARD_AXE						40009
#define ITEM_BOARD_HOLLY_WATER				40010
#define ITEM_BOARD_BOOMERANG				40012
#define ITEM_BOARD_STOPWATCH				40014
#define ITEM_BOARD_DOUBLE_SHOT				40015
#define ITEM_BOARD_TRIPLE_SHOT				40016


// money effect
#define MONEY_EFFECT_100						520
#define MONEY_EFFECT_400						521
#define MONEY_EFFECT_700						522
#define MONEY_EFFECT_1000						523
#define MONEY_EFFECT_2000						524

//Enemies
//BLACK_KNIGHT
#define BLACK_KNIGHT_HP 2
#define BLACK_KNIGHT_DAMAGE 1
#define BLACK_KNIGHT_WALKING_SPEED 0.015f

#define BLACK_KNIGHT_BBOX_WIDTH 16
#define BLACK_KNIGHT_BBOX_HEIGHT 32

#define BLACK_KNIGHT_STATE_WALKING 100
#define BLACK_KNIGHT_STATE_DIE 200


#define BLACK_KNIGHT_ANI_WALKING_LEFT  0
#define BLACK_KNIGHT_ANI_WALKING_RIGHT 1
#define BLACK_KNIGHT_ANI_DIE 1

#define BLACK_KNIGHT_FLYING_SPEED_X 0.05f
#define BLACK_KNIGHT_FLYING_SPEED_y 0.05f

#define BLACK_KNIGHT_DISTANCE_X 16

// VAMPIRE_BAT
#define VAMPIRE_BAT_HP 1
#define VAMPIRE_BAT_DAMAGE 1

#define VAMPIRE_BAT_BBOX_WIDTH 12
#define VAMPIRE_BAT_BBOX_HEIGHT 14


#define VAMPIRE_BAT_STATE_IDLE 100
#define VAMPIRE_BAT_STATE_FLYING 200
#define VAMPIRE_BAT_STATE_DIE 300

#define VAMPIRE_BAT_ANI_IDLE 0
#define VAMPIRE_BAT_ANI_BLACK_FLYING_LEFT	1
#define VAMPIRE_BAT_ANI_BLACK_FLYING_RIGHT	2
#define VAMPIRE_BAT_ANI_RED_FLYING_LEFT		3
#define VAMPIRE_BAT_ANI_RED_FLYING_RIGHT	4
#define VAMPIRE_BAT_ANI_DIE    5

#define VAMPIRE_BAT_DISTANCE_ATTACK_X 70